apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontorag.fullname" . }}-env
  labels:
    {{- include "ontorag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "ontorag.envContent" . | nindent 4 }}
